// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvaPUlbMjGalckJh-8M7toEUSCfK2y8oA',
    appId: '1:831081293351:web:88708e2a0be1912fc8d002',
    messagingSenderId: '831081293351',
    projectId: 'fir-flutter-codelab-4e7ed',
    authDomain: 'fir-flutter-codelab-4e7ed.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4e7ed.appspot.com',
    measurementId: 'G-EQQ5C67LK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt1EXN9u3gMaDl6sb7MjrAeR8uBHEQxQU',
    appId: '1:831081293351:android:47ef2ca32ee73a0ac8d002',
    messagingSenderId: '831081293351',
    projectId: 'fir-flutter-codelab-4e7ed',
    storageBucket: 'fir-flutter-codelab-4e7ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHVjZ0JaP69LgYcjMJD1vu8wQk2dCwNQ',
    appId: '1:831081293351:ios:24208d2ba379a2cbc8d002',
    messagingSenderId: '831081293351',
    projectId: 'fir-flutter-codelab-4e7ed',
    storageBucket: 'fir-flutter-codelab-4e7ed.appspot.com',
    iosClientId: '831081293351-dfbj1animfijpmq1tel6aukuk5995s1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZHVjZ0JaP69LgYcjMJD1vu8wQk2dCwNQ',
    appId: '1:831081293351:ios:24208d2ba379a2cbc8d002',
    messagingSenderId: '831081293351',
    projectId: 'fir-flutter-codelab-4e7ed',
    storageBucket: 'fir-flutter-codelab-4e7ed.appspot.com',
    iosClientId: '831081293351-dfbj1animfijpmq1tel6aukuk5995s1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
